spring.application.name=USER-SERVICE
server.port=8082

spring.mongodb.uri=mongodb://mongodb:27017/user_db
eureka.client.service-url.defaultZone=http://eureka:8761/eureka
jwt.secret=${JWT_SECRET}

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100

logging.level.org.springframework.core.env=TRACE


app.admin.enabled=true
app.admin.name=${ADMIN_NAME:Administrator}
app.admin.email=${ADMIN_EMAIL:admin@gmaail.com}
app.admin.password=${ADMIN_PASSWORD:admin1234}

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true